### ISSUE TITLE
How to set my values

### ISSUE THREAD

**Issue by louis-etne** [domschiener/smart-plant-raspberry#2]
Hello,  
Thanks for your tutorial, it was really god! (I don't know why but I can't comment on your website).

I got my values from my moisture sensor, in dry air, my moisture sensor send me 2 and in a glass of water, my sensor send me 835. Where do I put this values in your scripts ?

Except this, everything works like a charm!  
Thanks and have a nice day ! :smiley:

**Comment by domschiener** [comment]
Hello Louis,

thanks for reaching out :) Not sure why commenting on the blog doesn't work, need to look into that.

Basically these upper and lower bounds are necessary to determine the correct percentage of the measure we get. You should go into getdata.py and then search for "self.percent = 100 - int(round((self.adcOut - 300)/7.24))". 

As you see, in my tutorial I got 300 when the sensor was completely wet, and 1024 when the sensor was completely dry (so reversed from you). This means to get the right output I need to remove 300 from the value we get from the sensor (to remove the lower bound), then we divide it by 7.24 (which is 1024 - 300, basically the upper bound minus the lower bound). But these calculations are not relevant in your case, since everything seems to be working perfectly as is and we don't need to reverse or subtract any lower bound.

Therefore what you only need to change is the following:
self.percent = int(round(self.adcOut / 8.35))

This should give you the right percentage output :)
